language: node_js
node_js:
- '4'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
before_install:
- export CC="gcc-4.9" CXX="g++-4.9"
deploy:
  provider: npm
  email: seb.cottinet@gmail.com
  api_key:
    secure: hCjQu9WFmkpxv75G5qghlCzuHeEfzx4FTjv5RJcqr3dR736S5j/JvBRrkGeX7SEgih5/v4oByuStTe0+yEn7kc73YjSty32jVZrfS+NHkOSdDwtCxAxdppVDtaf6j9BOKT1KpjesJkYdNDjIr1LACbpV+3s8BuRfmqp0gsIMyrSL04jIOEvMowgOQ5RIn8RdcWSz2OUlGHiQM/CL6rR0y7ziBinUyKHzWdsjZZfKq29WfjFUo9h2nppC2l0X11PAKlQE/MDQpmS0IvlnTZjg6RsZ/WaHYOiSfF5Pq3SyIAcKMI8uWJWj87iH3/xpFHjV+fuqp/vBuWA7aQzfeIYVnHT+teeDNu8X4UzY2yOTprF8/L8hd/P87IcMQDAvPeSpjjoGwUr1+PWI+5dU55TtmgOAZQiWvWIPSTBO+Ee4hz9S/Xs+A5fL6vQ/g4ZmcPhWEvQ+YMvQKwpnO55ROI5Aszm25LLjUBx4HzhXETp5R88dxne4n96kzMHGiKI7ysz1UB8AzwMhH6lq3ejhu/Ocm3fU4AiRrdr3+F/HWBTNCYMQytSDbY/pDU9fFkAmdyorjh0c3vWDMCleRJViJmaiysshhduqjI9jE4zK1ikb0S6T6hQASgyq4y1AvR6ohIAy5lU+MBlvvwUrqx9MG3xOp7SDNViEdJ0G55Lk/yscPG0=
  on:
    repo: scottinet/espresso-logic-minimizer
    branch: master
